### ISSUE TITLE
Indexing non-mined transations

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/NBitcoin.Indexer#4]
Is there any method to index transactions sent to bitcoind (for example using RPC) and present in its memory but not mined by any miner yet?

It will have the use that already broadcasted transactions inputs can be assumed as spent to prevent further confusion in the applications using Indexer for example to build a stack of unconfirmed transactions on top of each other, without waiting for confirmation.

**Comment by NicolasDorier** [comment]
yes, actually you should take a look at my project QBitNinja. It depends on NBitcoin.Indexer and provide easy to use REST Service to query it.

More importantly, it has a console app "QBitNinja.Listener" which just index everything by listening a particular node.

**Comment by bijakatlykkex** [comment]
Thank you very much. I was missing it.
