### ISSUE TITLE
Error while importing entities

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/NBitcoin.Indexer#5]
When I run indexer from 3 different machines in parallel (on different blocks); I constantly get an exception similar to the following exception; but the indexer continues its operation (--All switch is used):

NBitcoin.Indexer Information: 0 : Blocks 335497/350000 (estimate : 18h 18m)
NBitcoin.Indexer Error: 0 : Error while importing entities (len:100) : StorageEx
ception: Unexpected response code for operation : 0   at Microsoft.WindowsAzure.
Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy po
licy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Table.TableBatchOperation.Execute(CloudTabl
eClient client, CloudTable table, TableRequestOptions requestOptions, OperationC
ontext operationContext)
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.ExecuteBatch(TableBatchOpe
ration batch, TableRequestOptions requestOptions, OperationContext operationCont
ext)
   at NBitcoin.Indexer.IndexTasks.IndexTableEntitiesTaskBase`1.IndexCore(String
partitionName, IEnumerable`1 items) in F:\Github\NBitcoin.Indexer\NBitcoin.Index
er\IndexTasks\IndexTableEntitiesTask.cs:line 132
.
.
.
.
[91] 51324790b0de1a4cf2c55ba95b5880ff458da29a073e2f6dcd1f46b55637d3ba-b-00000000
0000000012073a81d664b3f3bb7b6b196f0cb980b26389a81d3d470f
[92] 326ed13cdd476423e346521d57b1da7a50007bb2db7295c5b7ba7fd9f188c2ba-b-00000000
0000000012073a81d664b3f3bb7b6b196f0cb980b26389a81d3d470f
[93] 7df5f763abb016d9a0f531a7849b969883545346753eedc9d1c28bc0bd6ffcba-b-00000000
0000000012073a81d664b3f3bb7b6b196f0cb980b26389a81d3d470f
[94] 6a5b173a59ec275a846bd1ade01f094f70850d1ca73299c72da11dd80c89e2ba-b-00000000
000000000b4e0978b45f23bcd0cf2faa307a0d4163a65169634838f7
[95] c489c86a02c8466eda96fc3d949ac6153ad3f65b2f6d1857a64e32873a26ccba-b-00000000
000000000b4e0978b45f23bcd0cf2faa307a0d4163a65169634838f7
[96] 79cca99408599b7485cef451e7cab8f1e6a4bd6e5b212e9eab1fe1272263d8ba-b-00000000
0000000008901578acdca7ee97f810b0024b970b45c0ccfcc23a4d1e
[97] 5604f9c7ffb5be9baaa4e828f64e2a3b8b151434df491a68076f10c61746d7ba-b-00000000
0000000008901578acdca7ee97f810b0024b970b45c0ccfcc23a4d1e
[98] 8023eda657cbf682a348f8c3e235283cfaf1db5ba4a132f39042352aed1ce0ba-b-00000000
000000000dd79c7f0928721ed0041e98afc7a47bba68361cae336464
[99] c896d1cbb5f69c78e678e53b6244711827387e6071a3ba6be9b92074e3c1f2ba-b-00000000
000000000dd79c7f0928721ed0041e98afc7a47bba68361cae336464

It seems the error is generated near here: https://github.com/MetacoSA/NBitcoin.Indexer/blob/master/NBitcoin.Indexer/IndexTasks/IndexTableEntitiesTask.cs#L164 and since the exception is thrown; 

I wanted to know if the operation completes successfully in a retry or not?

**Comment by NicolasDorier** [comment]
Not a problem, the indexer retries. The problem is if it get stuck and stop moving forward.

**Comment by bijakatlykkex** [comment]
Thanks.

My doubt came from the line "batches.Enqueue(batch);" and then re throwing the exception; At first look it seems in this case of this error (despite the other 2 cases which do not re throw exception) the error is not retried. It seems I am missing something here.

**Comment by NicolasDorier** [comment]
One sec, I'm wondering as well why I am throwing after readding the batch to submit to the queue.

You can check if it was correclty indexed by querying 79cca99408599b7485cef451e7cab8f1e6a4bd6e5b212e9eab1fe1272263d8ba with the IndexerClient object though. Can you let me know ?

**Comment by bijakatlykkex** [comment]
It is actually being indexed for QBit.Ninja, I am assuming 79...ba to be a transaction id, and if I check with QBit.Ninja api for transactions, yes this transaction has been indexed.

Please inform me if I this method is not sufficient for checking.

**Comment by NicolasDorier** [comment]
That's fine no bug. Azure sends such error time to time, I think it is because of throttling, anyway, it has been indexed correctly, no problem.

**Comment by bijakatlykkex** [comment]
Thank you, I myself think, indexing has been done properly; But yet, I do not understand where does the re-indexing of the failed ones retried in the code.

One thing to note, is that before I try to use parallel machines to perform indexing I tried to use a single machine and because of the long time it took, I think I have tried blocks, transactions and etc. separately. The blocks seems to got complete at the time but I think I did not continue with transactions at the time completely. So, there is a very low probably that this transaction was indexed at that time (false positive case).

**Comment by NicolasDorier** [comment]
I retry here: https://github.com/MetacoSA/NBitcoin.Indexer/blob/master/NBitcoin.Indexer/IndexTasks/IndexTask.cs#L128

The retry object is of type ExponentialBackoff, it takes a lambda which is retried if it fails. (15 times max, then throw)

If you want to do mutli machine initial indexing, you should better use QBitNinja console app which distribute the work through a queue. (even if doing how you did is also fine, but less easy)

**Comment by bijakatlykkex** [comment]
Thanks very much for clarification.
